DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;

CREATE TABLE albums (
  id SERIAL PRIMARY KEY,D
  title VARCHAR(255),
  genre VARCHAR(255),
  artist VARCHAR(255)
);

CREATE TABLE artists (
  id SERIAL PRIMARY KEY,
  description VARCHAR(255),
  name VARCHAR(255)
);